### ISSUE TITLE
更新了下博客，然后博客挂掉了怎么破,报了好多错误，233

### ISSUE THREAD

**Issue by YBFJ** [Longlongyu/hexo-theme-Cxo#16]
```
ERROR Theme config load failed.
ERROR Process failed: _config.yml
YAMLException: duplicated mapping key at line 52, column 1:
    reading_info: true
    ^
    at generateError (/Users/CMJ/Desktop/YBFJ_Blog/Hexo/node_modules/js-yaml/lib/js-yaml/loader.js:165:10)
    at throwError (/Users/CMJ/Desktop/YBFJ_Blog/Hexo/node_modules/js-yaml/lib/js-yaml/loader.js:171:9)
    at storeMappingPair (/Users/CMJ/Desktop/YBFJ_Blog/Hexo/node_modules/js-yaml/lib/js-yaml/loader.js:308:7)
    at readBlockMapping (/Users/CMJ/Desktop/YBFJ_Blog/Hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1071:9)
    at composeNode (/Users/CMJ/Desktop/YBFJ_Blog/Hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1332:12)
    at readDocument (/Users/CMJ/Desktop/YBFJ_Blog/Hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1492:3)
    at loadDocuments (/Users/CMJ/Desktop/YBFJ_Blog/Hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1548:5)
    at Object.load (/Users/CMJ/Desktop/YBFJ_Blog/Hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1569:19)
    at Hexo.yamlHelper (/Users/CMJ/Desktop/YBFJ_Blog/Hexo/node_modules/hexo/lib/plugins/renderer/yaml.js:7:15)
    at Hexo.tryCatcher (/Users/CMJ/Desktop/YBFJ_Blog/Hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/CMJ/Desktop/YBFJ_Blog/Hexo/node_modules/bluebird/js/release/method.js:15:34)
    at Promise.then.text (/Users/CMJ/Desktop/YBFJ_Blog/Hexo/node_modules/hexo/lib/hexo/render.js:61:21)
    at tryCatcher (/Users/CMJ/Desktop/YBFJ_Blog/Hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/CMJ/Desktop/YBFJ_Blog/Hexo/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/CMJ/Desktop/YBFJ_Blog/Hexo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/CMJ/Desktop/YBFJ_Blog/Hexo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/CMJ/Desktop/YBFJ_Blog/Hexo/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/Users/CMJ/Desktop/YBFJ_Blog/Hexo/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/CMJ/Desktop/YBFJ_Blog/Hexo/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/CMJ/Desktop/YBFJ_Blog/Hexo/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/Users/CMJ/Desktop/YBFJ_Blog/Hexo/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
INFO  Files loaded in 2.17 s
ERROR /Users/CMJ/Desktop/YBFJ_Blog/Hexo/themes/Cxo/layout/includes/partial/head.pug:35
    33|   script(src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.js" defer)
    34|   // busuanzi
  > 35|   if (theme.count.busuanzi)
    36|     script(async src="//dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js")
    37| 

Cannot read property 'busuanzi' of undefined
TypeError: /Users/CMJ/Desktop/YBFJ_Blog/Hexo/themes/Cxo/layout/includes/partial/head.pug:35
    33|   script(src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.js" defer)
    34|   // busuanzi
  > 35|   if (theme.count.busuanzi)
    36|     script(async src="//dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js")
    37| 

```

**Comment by Longlongyu** [comment]
这是因为我更新了config，你对比一下冲突就可以发现。

reading_info 多写了一个，你要删掉一个，提交时候没有注意，请原谅我XD

busuanzi 现在被归到 count 的对象里了，你需要手动解决冲突，可以按下面方法来。

- 在 _config.yml 找到busuanzi
- 正常来说他应该像下面这样，如果不是，请修改成这样
``` yml
# access statistics
count:
  # enable analytics
  # true or flase
  busuanzi: true
  # baidu code
  baidu: 
```

**Comment by YBFJ** [comment]
噢噢好的，谢谢您，麻烦了~






在2018年10月6日 06:59，Mr.Long<notifications@github.com> 写道：

这是因为我更新了config，你对比一下冲突就可以发现。

reading_info 多写了一个，你要删掉一个，提交时候没有注意，请原谅我XD

busuanzi 现在被归到 count 的对象里了，你需要手动解决冲突，可以按下面方法来。

在 _config.yml 找到busuanzi
正常来说他应该像下面这样，如果不是，请修改成这样
# access statisticscount:
  # enable analytics# true or flasebusuanzi: true# baidu codebaidu:
